---
language: node_js
node_js:
  - '0.10'
  - '0.11'
  - '0.12'
  - 'iojs'
before_script:
  - 'npm run build'
  - 'npm run start 2>&1 > http.log &'
  - 'npm run phantom 2>&1 > phantom.log &'
after_script:
  - 'cat http.log'
  - 'cat phantom.log'
sudo: false
